### ISSUE TITLE
Map does not show in device (works with browser)

### ISSUE THREAD

**Issue by italomaia** [driftyco/ionic-starter-maps#10]
I created a new project with the maps template. When I run it with ionic (ionic serve), I'm able to see the map in my browser. Running the project in my device or emulator, after installing the platform, (ionic run android or ionic emulate android) the map does not load and I get a blank screen. What could be causing this?

**Comment by kmarrero** [comment]
add google maps to your whitelist

**Comment by italomaia** [comment]
I have this in config.xml:

    <access origin="*"/>
    <allow-navigation href="*" />

And I have this in my index.html:

     <meta http-equiv="Content-Security-Policy" content="default-src 'self' *"/>

Shouldn't it be enough?

**Comment by kmarrero** [comment]
I had to put

 <access origin="http://maps.google.com" />.

The map did not show up with <access origin="*"/> alone.

**Comment by italomaia** [comment]
<access origin="http://maps.google.com" />

Was it enough for you? I had a go and map still does not show in the device. Made a repo with my code. Could you take a look? https://github.com/italomaia/mymaps It is but a newly created project with the maps template where I added the new access rule to config.xml. I used "ionic run android" to test it on my device.

**Comment by kmarrero** [comment]
I tried this and it worked:
1. ionic start mymap maps
2. cd mymap
3. cordova platform add android
4. cordova build android

The map showed up without adding more to the whitelist than *. I seem to
have less issues with cordova builds. This assumes you installed cordova. I
typically only use ionic commands to get the starter files then switch
commands to cordova. I am using cordova 5.1.1.

**Comment by italomaia** [comment]
It worked! The problem was using ionic command line tool all along = (
Thanks kmarrero! Now I can sleep well again.

**Comment by franzisk** [comment]
Same problem here, I have in my config.xml:
  <access origin="http://maps.google.com" />

And I run:
cordova build android
cordova run android

The map is not showing in this device but in another one with Android 5.0 is showing OK, this one has Android 4.x.x

**Comment by hunkim** [comment]
Any solution? I got the same problem. It works i web browser, but not in the android/ios.

**Comment by kmarrero** [comment]
I added to my android manifest
<uses-library android:name="com.google.android.maps" />
My map had fatal error until I added this.

and to the config file
<allow-intent href="https://maps.googleapis.com"/>

**Comment by usamanoman** [comment]
Same problem....!

**Comment by kmarrero** [comment]
Did you add this:

android manifest
<uses-library android:name="com.google.android.maps" />

config file
<allow-intent href="https://maps.googleapis.com"/>

**Comment by errorstudent** [comment]
Hi, i have same problem, but my problem solved when i'm try to remove platform and then added again.

    $ionic platform rm android
    $ionic platform add android

it's work for me!

**Comment by Neseek77** [comment]
Adding just this

`<allow-navigation href="*" />`

 in my app's config.xml file solved this problem for me...

**Comment by gsanjeevkumar** [comment]
everything like you all said, is allowed however the maps do not load on the Android simulator and same on phones
all text and HTML is flowing in the app right, navigation works, data from external server (JSON) is coming thru. but no images and no google maps.
let me know if you guys have any ideas.
