### ISSUE TITLE
App freezes when pressing Locate Me

### ISSUE THREAD

**Issue by NBAMj** [driftyco/ionic-starter-maps#9]
For some reason, when I click on the Locate Me icon at the bottom left corner, the application freezes !
I'm using iPhone 5 (ios 8.3).

**Comment by davidhsv** [comment]
Same here, in iphone emulator iphone 6 ios 8.2.

**Comment by holographix** [comment]
+1

**Comment by benmarten** [comment]
Following this answer solved it for me:
http://stackoverflow.com/a/30742672/2302437

Basically it's missing the Location Permission Dialogue on iOS 8!

**Comment by rocco** [comment]
just do this:
```
ionic plugin add cordova-plugin-geolocation
```

**Comment by saaqibz** [comment]
+1 to rocco's fix
